version: '3.7'
services:
    grafana:
      container_name: ${APP_NAME}_grafana
      image: grafana/grafana:latest
      restart: always
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
        - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
        - GF_AUTH_ANONYMOUS_ENABLED=false
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
        - VIRTUAL_ROOT=/var/www/html
        - VIRTUAL_PORT=3000
        - LETSENCRYPT_HOST=${DOMAIN_NAME}
        - VIRTUAL_HOST=${DOMAIN_NAME}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      volumes:
        - grafana:/var/lib/grafana
      ports:
        - ${BACKEND_PORT}:3000
      networks:
        - monitor_net

    grafana-setup:
      container_name: ${APP_NAME}_grafana-setup
      image: sitespeedio/grafana-bootstrap:latest
      depends_on:
        - grafana
      environment:
        - GF_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
        - GF_USER=${GF_SECURITY_ADMIN_USER}
      networks:
        - monitor_net

    prometheus:
      container_name: ${APP_NAME}_prometheus
      image: prom/prometheus
      restart: always
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      volumes:
        - ./prometheus/:/etc/prometheus/
        - prometheus_data:/prometheus
      ports:
        - 9090:9090
      networks:
        - monitor_net

volumes:
  prometheus_data:
  grafana:

networks:
  monitor_net:
    name: monitor_net
